### ISSUE TITLE
Swedish characters doesn't seem to work

### ISSUE THREAD

**Issue by UnluckyLuke** [dossy/hanewinpgp#1]
It doesn't seem to handle Swedish characters like Å Ä Ö å ä ö.

**Comment by dossy** [comment]
@UnluckyLuke, I just tried to reproduce, encrypting/decrypting those specific characters, using Chrome 61.0.3163.100 on MacOS X 10.11.6, and it worked as expected, successfully round-tripping those characters just fine.

Can you provide details around how you're able to demonstrate this failure and/or provide enough information so that I can reproduce the failure?

Thanks!

**Comment by dossy** [comment]
@UnluckyLuke, if you can provide instructions on how I can reproduce the problem, I'd appreciate it.  When I use the [demo page](https://dossy.github.io/hanewinpgp/demo-encrypt/) and paste in the characters you provided, I get back the original text exactly as expected.  This is on MacOS X 10.11.6 El Capitan using Chrome 62.

I'm going to go ahead and close this issue, but if you can provide instructions on how to reproduce, feel free to go ahead and re-open it.  Thanks!
